services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports: ["5432:5432"]
#    volumes:
#      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8080"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      OIDC_ISSUER_URL: http://keycloak:8080/realms/todos
      OIDC_ISSUER_URL_EXTERNAL: http://localhost:8081/realms/todos
      OIDC_AUDIENCE: todos-api
      # MinIO configuration
      S3_BUCKET_NAME: todos-files
      S3_ENDPOINT_URL: http://minio:9000
      S3_PUBLIC_ENDPOINT_URL: http://localhost:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      AWS_REGION: us-east-1
    depends_on: [db, keycloak, minio]
    ports: ["8000:8000"]
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build: ./frontend
    environment:
      API_URL: http://localhost:8000
      OIDC_AUTHORITY: http://localhost:8081/realms/todos
      OIDC_CLIENT_ID: todos-spa
      OIDC_REDIRECT_URI: http://localhost:8080/auth/callback
      OIDC_POST_LOGOUT_REDIRECT_URI: http://localhost:8080/
      OIDC_SCOPE: openid profile email
    depends_on: [backend]
    ports: ["8080:80"]

  prometheus:
    build: ./prometheus
    ports: ["9090:9090"]
    environment:
      BACKEND_TARGET: backend:8000
    depends_on: [backend]
    volumes:
      - prometheus_data:/prometheus

  grafana:
    build: ./grafana
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      PROMETHEUS_URL: http://prometheus:9090
    depends_on: [prometheus]
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
#  db_data:
  backend_uploads:
  minio_data:
  prometheus_data:
  grafana_data:
